// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: name_serv.proto

#ifndef PROTOBUF_name_5fserv_2eproto__INCLUDED
#define PROTOBUF_name_5fserv_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace dist_storage {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_name_5fserv_2eproto();
void protobuf_AssignDesc_name_5fserv_2eproto();
void protobuf_ShutdownFile_name_5fserv_2eproto();

class HBRequest;
class HBResponse;

enum DSCode {
  SUC = 0,
  ERR = 1
};
bool DSCode_IsValid(int value);
const DSCode DSCode_MIN = SUC;
const DSCode DSCode_MAX = ERR;
const int DSCode_ARRAYSIZE = DSCode_MAX + 1;

const ::google::protobuf::EnumDescriptor* DSCode_descriptor();
inline const ::std::string& DSCode_Name(DSCode value) {
  return ::google::protobuf::internal::NameOfEnum(
    DSCode_descriptor(), value);
}
inline bool DSCode_Parse(
    const ::std::string& name, DSCode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<DSCode>(
    DSCode_descriptor(), name, value);
}
enum NodeAction {
  Reg = 0,
  UnReg = 1,
  Beat = 2,
  NUL = 3
};
bool NodeAction_IsValid(int value);
const NodeAction NodeAction_MIN = Reg;
const NodeAction NodeAction_MAX = NUL;
const int NodeAction_ARRAYSIZE = NodeAction_MAX + 1;

const ::google::protobuf::EnumDescriptor* NodeAction_descriptor();
inline const ::std::string& NodeAction_Name(NodeAction value) {
  return ::google::protobuf::internal::NameOfEnum(
    NodeAction_descriptor(), value);
}
inline bool NodeAction_Parse(
    const ::std::string& name, NodeAction* value) {
  return ::google::protobuf::internal::ParseNamedEnum<NodeAction>(
    NodeAction_descriptor(), name, value);
}
// ===================================================================

class HBRequest : public ::google::protobuf::Message {
 public:
  HBRequest();
  virtual ~HBRequest();

  HBRequest(const HBRequest& from);

  inline HBRequest& operator=(const HBRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HBRequest& default_instance();

  void Swap(HBRequest* other);

  // implements Message ----------------------------------------------

  HBRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HBRequest& from);
  void MergeFrom(const HBRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string host = 1 [default = ""];
  inline bool has_host() const;
  inline void clear_host();
  static const int kHostFieldNumber = 1;
  inline const ::std::string& host() const;
  inline void set_host(const ::std::string& value);
  inline void set_host(const char* value);
  inline void set_host(const char* value, size_t size);
  inline ::std::string* mutable_host();
  inline ::std::string* release_host();
  inline void set_allocated_host(::std::string* host);

  // optional .dist_storage.NodeAction action = 2 [default = NUL];
  inline bool has_action() const;
  inline void clear_action();
  static const int kActionFieldNumber = 2;
  inline ::dist_storage::NodeAction action() const;
  inline void set_action(::dist_storage::NodeAction value);

  // optional int64 updated_time = 3 [default = 0];
  inline bool has_updated_time() const;
  inline void clear_updated_time();
  static const int kUpdatedTimeFieldNumber = 3;
  inline ::google::protobuf::int64 updated_time() const;
  inline void set_updated_time(::google::protobuf::int64 value);

  // optional int64 avail_space = 4 [default = 0];
  inline bool has_avail_space() const;
  inline void clear_avail_space();
  static const int kAvailSpaceFieldNumber = 4;
  inline ::google::protobuf::int64 avail_space() const;
  inline void set_avail_space(::google::protobuf::int64 value);

  // optional int64 visit_flow = 5 [default = 0];
  inline bool has_visit_flow() const;
  inline void clear_visit_flow();
  static const int kVisitFlowFieldNumber = 5;
  inline ::google::protobuf::int64 visit_flow() const;
  inline void set_visit_flow(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:dist_storage.HBRequest)
 private:
  inline void set_has_host();
  inline void clear_has_host();
  inline void set_has_action();
  inline void clear_has_action();
  inline void set_has_updated_time();
  inline void clear_has_updated_time();
  inline void set_has_avail_space();
  inline void clear_has_avail_space();
  inline void set_has_visit_flow();
  inline void clear_has_visit_flow();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* host_;
  ::google::protobuf::int64 updated_time_;
  ::google::protobuf::int64 avail_space_;
  ::google::protobuf::int64 visit_flow_;
  int action_;
  friend void  protobuf_AddDesc_name_5fserv_2eproto();
  friend void protobuf_AssignDesc_name_5fserv_2eproto();
  friend void protobuf_ShutdownFile_name_5fserv_2eproto();

  void InitAsDefaultInstance();
  static HBRequest* default_instance_;
};
// -------------------------------------------------------------------

class HBResponse : public ::google::protobuf::Message {
 public:
  HBResponse();
  virtual ~HBResponse();

  HBResponse(const HBResponse& from);

  inline HBResponse& operator=(const HBResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HBResponse& default_instance();

  void Swap(HBResponse* other);

  // implements Message ----------------------------------------------

  HBResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HBResponse& from);
  void MergeFrom(const HBResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .dist_storage.DSCode code = 1 [default = SUC];
  inline bool has_code() const;
  inline void clear_code();
  static const int kCodeFieldNumber = 1;
  inline ::dist_storage::DSCode code() const;
  inline void set_code(::dist_storage::DSCode value);

  // @@protoc_insertion_point(class_scope:dist_storage.HBResponse)
 private:
  inline void set_has_code();
  inline void clear_has_code();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int code_;
  friend void  protobuf_AddDesc_name_5fserv_2eproto();
  friend void protobuf_AssignDesc_name_5fserv_2eproto();
  friend void protobuf_ShutdownFile_name_5fserv_2eproto();

  void InitAsDefaultInstance();
  static HBResponse* default_instance_;
};
// ===================================================================

class NameSevice_Stub;

class NameSevice : public ::google::protobuf::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline NameSevice() {};
 public:
  virtual ~NameSevice();

  typedef NameSevice_Stub Stub;

  static const ::google::protobuf::ServiceDescriptor* descriptor();

  virtual void HeartBeat(::google::protobuf::RpcController* controller,
                       const ::dist_storage::HBRequest* request,
                       ::dist_storage::HBResponse* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::google::protobuf::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::google::protobuf::MethodDescriptor* method,
                  ::google::protobuf::RpcController* controller,
                  const ::google::protobuf::Message* request,
                  ::google::protobuf::Message* response,
                  ::google::protobuf::Closure* done);
  const ::google::protobuf::Message& GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const;
  const ::google::protobuf::Message& GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(NameSevice);
};

class NameSevice_Stub : public NameSevice {
 public:
  NameSevice_Stub(::google::protobuf::RpcChannel* channel);
  NameSevice_Stub(::google::protobuf::RpcChannel* channel,
                   ::google::protobuf::Service::ChannelOwnership ownership);
  ~NameSevice_Stub();

  inline ::google::protobuf::RpcChannel* channel() { return channel_; }

  // implements NameSevice ------------------------------------------

  void HeartBeat(::google::protobuf::RpcController* controller,
                       const ::dist_storage::HBRequest* request,
                       ::dist_storage::HBResponse* response,
                       ::google::protobuf::Closure* done);
 private:
  ::google::protobuf::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(NameSevice_Stub);
};


// ===================================================================


// ===================================================================

// HBRequest

// optional string host = 1 [default = ""];
inline bool HBRequest::has_host() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HBRequest::set_has_host() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HBRequest::clear_has_host() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HBRequest::clear_host() {
  if (host_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    host_->clear();
  }
  clear_has_host();
}
inline const ::std::string& HBRequest::host() const {
  // @@protoc_insertion_point(field_get:dist_storage.HBRequest.host)
  return *host_;
}
inline void HBRequest::set_host(const ::std::string& value) {
  set_has_host();
  if (host_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    host_ = new ::std::string;
  }
  host_->assign(value);
  // @@protoc_insertion_point(field_set:dist_storage.HBRequest.host)
}
inline void HBRequest::set_host(const char* value) {
  set_has_host();
  if (host_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    host_ = new ::std::string;
  }
  host_->assign(value);
  // @@protoc_insertion_point(field_set_char:dist_storage.HBRequest.host)
}
inline void HBRequest::set_host(const char* value, size_t size) {
  set_has_host();
  if (host_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    host_ = new ::std::string;
  }
  host_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:dist_storage.HBRequest.host)
}
inline ::std::string* HBRequest::mutable_host() {
  set_has_host();
  if (host_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    host_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:dist_storage.HBRequest.host)
  return host_;
}
inline ::std::string* HBRequest::release_host() {
  clear_has_host();
  if (host_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = host_;
    host_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void HBRequest::set_allocated_host(::std::string* host) {
  if (host_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete host_;
  }
  if (host) {
    set_has_host();
    host_ = host;
  } else {
    clear_has_host();
    host_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:dist_storage.HBRequest.host)
}

// optional .dist_storage.NodeAction action = 2 [default = NUL];
inline bool HBRequest::has_action() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void HBRequest::set_has_action() {
  _has_bits_[0] |= 0x00000002u;
}
inline void HBRequest::clear_has_action() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void HBRequest::clear_action() {
  action_ = 3;
  clear_has_action();
}
inline ::dist_storage::NodeAction HBRequest::action() const {
  // @@protoc_insertion_point(field_get:dist_storage.HBRequest.action)
  return static_cast< ::dist_storage::NodeAction >(action_);
}
inline void HBRequest::set_action(::dist_storage::NodeAction value) {
  assert(::dist_storage::NodeAction_IsValid(value));
  set_has_action();
  action_ = value;
  // @@protoc_insertion_point(field_set:dist_storage.HBRequest.action)
}

// optional int64 updated_time = 3 [default = 0];
inline bool HBRequest::has_updated_time() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void HBRequest::set_has_updated_time() {
  _has_bits_[0] |= 0x00000004u;
}
inline void HBRequest::clear_has_updated_time() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void HBRequest::clear_updated_time() {
  updated_time_ = GOOGLE_LONGLONG(0);
  clear_has_updated_time();
}
inline ::google::protobuf::int64 HBRequest::updated_time() const {
  // @@protoc_insertion_point(field_get:dist_storage.HBRequest.updated_time)
  return updated_time_;
}
inline void HBRequest::set_updated_time(::google::protobuf::int64 value) {
  set_has_updated_time();
  updated_time_ = value;
  // @@protoc_insertion_point(field_set:dist_storage.HBRequest.updated_time)
}

// optional int64 avail_space = 4 [default = 0];
inline bool HBRequest::has_avail_space() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void HBRequest::set_has_avail_space() {
  _has_bits_[0] |= 0x00000008u;
}
inline void HBRequest::clear_has_avail_space() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void HBRequest::clear_avail_space() {
  avail_space_ = GOOGLE_LONGLONG(0);
  clear_has_avail_space();
}
inline ::google::protobuf::int64 HBRequest::avail_space() const {
  // @@protoc_insertion_point(field_get:dist_storage.HBRequest.avail_space)
  return avail_space_;
}
inline void HBRequest::set_avail_space(::google::protobuf::int64 value) {
  set_has_avail_space();
  avail_space_ = value;
  // @@protoc_insertion_point(field_set:dist_storage.HBRequest.avail_space)
}

// optional int64 visit_flow = 5 [default = 0];
inline bool HBRequest::has_visit_flow() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void HBRequest::set_has_visit_flow() {
  _has_bits_[0] |= 0x00000010u;
}
inline void HBRequest::clear_has_visit_flow() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void HBRequest::clear_visit_flow() {
  visit_flow_ = GOOGLE_LONGLONG(0);
  clear_has_visit_flow();
}
inline ::google::protobuf::int64 HBRequest::visit_flow() const {
  // @@protoc_insertion_point(field_get:dist_storage.HBRequest.visit_flow)
  return visit_flow_;
}
inline void HBRequest::set_visit_flow(::google::protobuf::int64 value) {
  set_has_visit_flow();
  visit_flow_ = value;
  // @@protoc_insertion_point(field_set:dist_storage.HBRequest.visit_flow)
}

// -------------------------------------------------------------------

// HBResponse

// optional .dist_storage.DSCode code = 1 [default = SUC];
inline bool HBResponse::has_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HBResponse::set_has_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HBResponse::clear_has_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HBResponse::clear_code() {
  code_ = 0;
  clear_has_code();
}
inline ::dist_storage::DSCode HBResponse::code() const {
  // @@protoc_insertion_point(field_get:dist_storage.HBResponse.code)
  return static_cast< ::dist_storage::DSCode >(code_);
}
inline void HBResponse::set_code(::dist_storage::DSCode value) {
  assert(::dist_storage::DSCode_IsValid(value));
  set_has_code();
  code_ = value;
  // @@protoc_insertion_point(field_set:dist_storage.HBResponse.code)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace dist_storage

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::dist_storage::DSCode> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::dist_storage::DSCode>() {
  return ::dist_storage::DSCode_descriptor();
}
template <> struct is_proto_enum< ::dist_storage::NodeAction> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::dist_storage::NodeAction>() {
  return ::dist_storage::NodeAction_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_name_5fserv_2eproto__INCLUDED
